---
title: "mouse_analysis"
author: "Kate Petrenko"
date: "2024-07-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(data.table)
library(Seurat)
library(scDblFinder)
library(DoubletFinder)
library(dplyr)
library(remotes)
# remotes::install_github("carmonalab/STACAS")
library(STACAS)
library(SingleR)
# install.packages("scGate")
library(scGate)
library(ggplot2)
library(BiocParallel)
# BiocManager::install("harmony")
library(harmony)
library(RColorBrewer)
library(stringr)
library(cowplot)
library(scuttle)
# install.packages("devtools")
# BiocManager::install("Homo.sapiens")
# BiocManager::install("jpmam1/scalop") #forked copy of a really good guy
# devtools::install_github("jlaffy/infercna")
library(infercna)
# library(infercnv)
library(parallel)
library(future)
library(clustree)
library(dittoSeq)
# install.packages("ggh4x")
library(ggh4x)
# BiocManager::install('EnhancedVolcano')
library(EnhancedVolcano)
library(clusterProfiler)
# BiocManager::install('org.Mm.eg.db')
library("org.Mm.eg.db")
# BiocManager::install('ReactomePA')
library(ReactomePA)
# BiocManager::install('msigdbr')
library(msigdbr)
# install.packages('qs')
library(qs)
# BiocManager::install('enrichR')
library(enrichR)
```

```{r global variables, include=FALSE}
set.seed(100)
DATADIR = '~/neuroblastoma/data/'
WORKDIR = '~/neuroblastoma/'
PREPRDATADIR = '~/neuroblastoma/preprocessing_data/'

my_colors <- c("#6495EDFF", "#FF69B4FF", "#BA55D3FF",  "#F08080FF", "#32CD32FF",  
               "#9ACD32FF", "#4682B4FF",  "#DDA0DDFF", "#FFA07AFF", "#8FBC8BFF",
               "#40E0D0FF",  "#F0E68CFF", "#5F9EA0FF", "#D2B48CFF",  
               "#FFDAB9FF",  "#87CEEBFF")
```

```{r download references, message=FALSE, warning=FALSE, include=FALSE}
mouse_ref <- celldex::MouseRNAseqData()
mouse_ref_imm <- celldex::ImmGenData()
scGate_models_DB <- get_scGateDB()
```

```{r}

annotate <- function(seu) {
  
  seu <- seu %>% 
    NormalizeData() %>%
    FindVariableFeatures()%>%
    ScaleData() %>%
    RunPCA() %>% 
    RunUMAP(dims = 1:20) %>%
    FindNeighbors(dims = 1:20) %>%
    FindClusters(resolution = 1.5)
  
  sce <- as.SingleCellExperiment(seu)
  colLabels(sce) <- seu$RNA_snn_res.1.5
  Idents(seu) <- 'RNA_snn_res.1.5'
  
  print('singler')
  # #cluster-wise annotation
  pred_bped_main <- SingleR(test = sce, ref = mouse_ref, clusters=colLabels(sce),
                            labels = mouse_ref$label.main, BPPARAM=MulticoreParam(30))
  # # Create a named vector for RenameIdents
  singleR_labels <- pred_bped_main$pruned.labels
  names(singleR_labels) <- rownames(pred_bped_main)
  
  # Update cluster identities in Seurat object based on SingleR results
  seu <- RenameIdents(seu, singleR_labels)
  seu[['SingleR_labels']] <- Idents(seu)
  print('scgate')
  # define malignant cells
  malignant_scGate_model <- gating_model(name = "Malignant", signature = c("MYCN"))
  seu <- scGate(data = seu, model = malignant_scGate_model)
  barcode_malignant <- unique(c(colnames(seu)[seu$is.pure == 'Pure']))
  print('stromal')
  # define stromal cells
  stromal_scGate_model <- gating_model(name = "Stromal", 
                                       signature = c('Mmp2', 'Col1a1', 'Col1a2', 'Col5a1', 'Lum', 'Pdgfra'), level = 1)
  stromal_scGate_model <- gating_model(stromal_scGate_model, name = 'Epithelial', 
                                      signature = c('Cdh1', 'Flt1'), level = 1)
  seu <- scGate(seu, model = stromal_scGate_model)
  barcode_stromal <- colnames(seu)[seu$is.pure == 'Pure']
  print('scgate T cell')
  #define t-cells
  seu <- scGate(seu, model = scGate_models_DB$mouse$generic$Tcell)
  barcode_T <- colnames(seu)[seu$is.pure == 'Pure']
  print('B cell')
  #define b-cells
  bcells_scGate_model <- gating_model(name = "PanBcell", signature = c('Cd79a'), level = 1)
  bcells_scGate_model <- gating_model(bcells_scGate_model, name = 'Bcell', 
                                      signature = c('Ms4a1', 'Bank1', 'Pax5', 'Cd19'), level = 2)
  bcells_scGate_model <- gating_model(bcells_scGate_model, name = 'Plasma_cell', 
                                      signature = c('Igkc', 'Ighg3', 'Ighg1', 'Igha', 'Cd19-'), level = 2)
  seu <- scGate(seu, model = bcells_scGate_model)
  barcode_B <- colnames(seu)[seu$is.pure == 'Pure']
  print('Myeloid')
  #define myeloid cells
  seu <- scGate(seu, model = scGate_models_DB$mouse$generic$Myeloid)
  barcode_myeloid <- colnames(seu)[seu$is.pure == 'Pure']
  
  seu <- scGate(seu, model = scGate_models_DB$mouse$generic$MoMacDC)
  barcode_monocyte <- colnames(seu)[seu$is.pure == 'Pure']
   print('final labels')
  # Assign final labels
  seu$final_labels <- "unknown"
  seu$final_labels[colnames(seu) %in% barcode_malignant] <- "malignant_cells"
  seu$final_labels[colnames(seu) %in% barcode_T] <- "T_cells"
  seu$final_labels[colnames(seu) %in% barcode_B] <- "B_cells"
  seu$final_labels[colnames(seu) %in% barcode_myeloid] <- "myeloid_cells"
  seu$final_labels[colnames(seu) %in% barcode_monocyte] <- "myeloid_cells"
  seu$final_labels[colnames(seu) %in% barcode_stromal] <- "stromal_cells"
  
  annot_comp <- c("Adipocytes" = 'weird',
                  "Neurons" = 'malignant_cells',
                  "Astrocytes" = 'weird',
                  "Endothelial cells" = 'stromal_cells',
                  "Erythrocytes" = 'weird',
                  "Fibroblasts" = 'malignant_cells',      
                  "Granulocytes" = 'myeloid_cells',
                  "Macrophages" = 'myeloid_cells',
                  "Microglia" = 'weird',
                  "Monocytes" = 'myeloid_cells',
                  "NK cells" = 'T_cells',
                  "Oligodendrocytes" = 'weird',
                  "T cells" = 'T_cells',
                  "Dendritic cells" = 'weird',
                  "Cardiomyocytes" = 'weird',
                  "Hepatocytes" = 'weird',
                  "B cells" = 'B_cells',
                  "Epithelial cells" = 'stromal_cells', 
                  'unknown' = 'unknown')
  
  pred_bped_main$pruned.labels[is.na(pred_bped_main$pruned.labels)] <- 'unknown'
  
  pred_bped_main$pruned.labels <- annot_comp[as.character(pred_bped_main$pruned.labels)]
  
  final_annotation_df <- data.frame(cluster = rownames(pred_bped_main),
                                    annotation = '-')
  # Compare SingleR and scGate
  for (i in rownames(pred_bped_main)) {
    
    if (table(seu$RNA_snn_res.1.5)[i] == 0) {
      next
    }
    
    cells_cluster <- seu[, colnames(seu) %in%  colnames(seu)[seu$RNA_snn_res.1.5 == i]]
    SingleR_title <- pred_bped_main$pruned.labels[rownames(pred_bped_main) == i]
    scGate_max <- names(which.max(table(cells_cluster$final_labels)))
    scGate_max2 <- names(table(cells_cluster$final_labels) %>% sort(decreasing = T))[2]
    scGate_max2 <- ifelse(is.na(scGate_max2), 'unknown', scGate_max2)
    
    if (scGate_max == SingleR_title & scGate_max != 'unknown') {
      final_annotation_df$annotation[final_annotation_df$cluster == i] <- scGate_max
    } else if (scGate_max2 == SingleR_title & scGate_max2 != 'unknown') {
      final_annotation_df$annotation[final_annotation_df$cluster == i] <- scGate_max2
    } else if (scGate_max == 'unknown' & SingleR_title != 'unknown') {
      final_annotation_df$annotation[final_annotation_df$cluster == i] <- SingleR_title
    } else if (scGate_max != 'unknown' & SingleR_title == 'unknown') {
      final_annotation_df$annotation[final_annotation_df$cluster == i] <- scGate_max
    } else {
      final_annotation_df$annotation[final_annotation_df$cluster == i] <- 'unresolved'
    }
    
  }
  
  final_annotation <- final_annotation_df$annotation
  names(final_annotation) <- final_annotation_df$cluster
  
  Idents(seu) <- 'RNA_snn_res.1.5'
  seu <- RenameIdents(seu, final_annotation)
  seu[['ANNOTATION_FINAL']] <- Idents(seu)
  
  return(seu)
  
}
```

# Read data
```{r}
young <- Read10X_h5(paste0(DATADIR,
                           'mice_scRNA-seq_v1/20240625_YuvalShaked_Chen/CellRanger_neutrophils/sample_P/outs/filtered_feature_bc_matrix.h5'))
adult <- Read10X_h5(paste0(DATADIR,
                           'mice_scRNA-seq_v1/20240625_YuvalShaked_Chen/CellRanger_neutrophils/sample_A/outs/filtered_feature_bc_matrix.h5'))
```

# Young

## Before

```{r}
young <- CreateSeuratObject(young, min.cells = 10, min.features = 200)
young$age <- 'young'
young[["percent.mt"]] <- PercentageFeatureSet(young, pattern = "^mt-")
# young[["percent.ribo"]] <- PercentageFeatureSet(young, pattern = "^Rp[sl]")
young[["complexity"]] <- log10(young$nFeature_RNA) / log10(young$nCount_RNA)
VlnPlot(young, c("nFeature_RNA", "nCount_RNA", "percent.mt", "complexity"), ncol = 4)
```

```{r include=FALSE}
young_ann <- annotate(young)

DimPlot(young_ann, group.by = 'SingleR_labels')
DimPlot(young_ann, group.by = 'final_labels')
DimPlot(young_ann, group.by = 'ANNOTATION_FINAL')
FeaturePlot(young_ann, 'Mycn')
FeaturePlot(young_ann, 'complexity')
FeaturePlot(young_ann, 'percent.mt')
FeaturePlot(young_ann, 'nFeature_RNA')
```

```{r fig.height=9, fig.width=12}
neutrophil_markers <- c("S100a8", "S100a9", "Lyz2", "Mpo", "Csf3r", "Itgam", "Ifitm3", "Fcgr3", "Ly6g", "Cd11b")
FeaturePlot(young_ann, neutrophil_markers)
```

```{r}
# Define neutrophil markers (based on literature)
neutrophil_markers <- c("S100a8", "S100a9", "Csf3r", "Cxcr2", "Cxcr4", "Sell", "Cd63", 
                       "Itgam", "Fcgr3", "Mmp9", "Elane", "Prtn3", "Mpo", "Ltf")

neutrophil_markers <- c("S100a8", "S100a9", "Lyz2", "Mpo", "Csf3r", "Itgam", "Ifitm3", "Fcgr3", "Ly6g", "Cd11b")
# Calculate neutrophil score
young_ann <- AddModuleScore(young_ann, 
                          features = list(neutrophil_markers),
                          name = "neutrophil_score")

# Plot feature counts distribution
p1 <- ggplot(young_ann@meta.data, aes(x=log2(nFeature_RNA))) +
      geom_density() +
      theme_classic() +
      ggtitle("Distribution of Gene Counts (Log2)")

print(p1)
```

```{r}
feature_cutoff_min <- 2^9  # removes left peak (empty droplets)
feature_cutoff_max <- 2^13 # Setting a high upper limit to keep all real cells

# Filter cells
young <- subset(young, subset = nFeature_RNA > feature_cutoff_min &
                                  nFeature_RNA < feature_cutoff_max &
                                  percent.mt < 15)
VlnPlot(young, c("nFeature_RNA", "nCount_RNA", "percent.mt", "complexity"), ncol = 4)
```

# Adult 

## Before

```{r}
adult <- CreateSeuratObject(adult, min.cells = 10, min.features = 200)
adult$age <- 'adult'
adult[["percent.mt"]] <- PercentageFeatureSet(adult, pattern = "^mt-")
# adult[["percent.ribo"]] <- PercentageFeatureSet(adult, pattern = "^Rp[sl]")
adult[["complexity"]] <- log10(adult$nFeature_RNA) / log10(adult$nCount_RNA)
VlnPlot(adult, c("nFeature_RNA", "nCount_RNA", "percent.mt", "complexity"), ncol = 4)
```

```{r include=FALSE}
adult_ann <- annotate(adult)

DimPlot(adult_ann, group.by = 'SingleR_labels')
DimPlot(adult_ann, group.by = 'final_labels')
DimPlot(adult_ann, group.by = 'ANNOTATION_FINAL')
FeaturePlot(adult_ann, 'Mycn')
FeaturePlot(adult_ann, 'complexity')
FeaturePlot(adult_ann, 'percent.mt')
FeaturePlot(adult_ann, 'nFeature_RNA')
```

```{r fig.height=9, fig.width=12}
neutrophil_markers <- c("S100a8", "S100a9", "Lyz2", "Mpo", "Csf3r", "Itgam", "Ifitm3", "Fcgr3", "Ly6g", "Cd11b")
FeaturePlot(adult_ann, neutrophil_markers)
```

```{r}
# Define neutrophil markers (based on literature)
neutrophil_markers <- c("S100a8", "S100a9", "Csf3r", "Cxcr2", "Cxcr4", "Sell", "Cd63", 
                       "Itgam", "Fcgr3", "Mmp9", "Elane", "Prtn3", "Mpo", "Ltf")

neutrophil_markers <- c("S100a8", "S100a9", "Lyz2", "Mpo", "Csf3r", "Itgam", "Ifitm3", "Fcgr3", "Ly6g", "Cd11b")
# Calculate neutrophil score
adult_ann <- AddModuleScore(adult_ann, 
                          features = list(neutrophil_markers),
                          name = "neutrophil_score")

# Plot feature counts distribution
p1 <- ggplot(adult_ann@meta.data, aes(x=log2(nFeature_RNA))) +
      geom_density() +
      theme_classic() +
      ggtitle("Distribution of Gene Counts (Log2)")

print(p1)
```

```{r}
feature_cutoff_min <- 2^9  # removes left peak (empty droplets)
feature_cutoff_max <- 2^13 # Setting a high upper limit to keep all real cells

# Filter cells
adult <- subset(adult, subset = nFeature_RNA > feature_cutoff_min &
                                  nFeature_RNA < feature_cutoff_max &
                                  percent.mt < 15)
VlnPlot(adult, c("nFeature_RNA", "nCount_RNA", "percent.mt", "complexity"), ncol = 4)
```

```{r include=FALSE}
annotated_samples <- lapply(list(young, adult),
                              annotate)

names(annotated_samples) <- c('P', 'A')

DimPlot(annotated_samples[[1]], group.by = 'ANNOTATION_FINAL')
DimPlot(annotated_samples[[2]], group.by = 'ANNOTATION_FINAL')

FeaturePlot(annotated_samples[[1]], 'Mycn')
FeaturePlot(annotated_samples[[2]], 'Mycn')
```

```{r}
seu <- merge(annotated_samples[[1]], annotated_samples[[2]], add.cell.ids = c("P", "A"))
```

## Integration

```{r include=FALSE}
seu <- seu %>% 
  NormalizeData() %>% 
  FindVariableFeatures() %>% 
  ScaleData() %>% 
  RunPCA(verbose=FALSE)
  
# seu <- seu %>% 
#   IntegrateLayers(
#     object = ., method = CCAIntegration,
#     orig.reduction = "pca", new.reduction = "integrated.cca",
#     verbose = FALSE) %>% 
#   RunUMAP(reduction = "integrated.cca", dims = 1:20) 

seu <- seu %>% 
  RunHarmony(., 'age',
             lambda = 1, verbose = FALSE) %>% 
  RunUMAP(reduction = "harmony", dims = 1:20, verbose=F) 

seu <- JoinLayers(seu)

DimPlot(seu, group.by = 'age', cols = my_colors) 
DimPlot(seu, group.by = 'ANNOTATION_FINAL', cols = my_colors) 
DimPlot(seu, group.by = 'SingleR_labels', cols = my_colors)
DimPlot(seu, group.by = 'final_labels', cols = my_colors) 
FeaturePlot(seu, 'Mycn')
```

```{r eval=FALSE, include=FALSE}
FeaturePlot(seu, 'Mycn')
FeaturePlot(seu, 'complexity')
FeaturePlot(seu, 'percent.mt')
FeaturePlot(seu, 'nFeature_RNA')
```
```{r fig.height=9, fig.width=12}
FeaturePlot(seu, neutrophil_markers)
```

```{r eval=FALSE, include=FALSE}
DimPlot(seu, group.by = 'RNA_snn_res.0.2', cols = my_colors) 
```

```{r include=FALSE}
seu <- seu %>% 
  FindNeighbors(dims = 1:10) %>%
  FindClusters(resolution = c(0.1, 0.2, 0.3, 0.4, 0.5)) 

# clustree(seu)

Idents(object = seu) <- "RNA_snn_res.0.2"

new.cluster.ids <- c('0'='Malignant_cells',
                     '1'='Malignant_cells',
                     '2'='Malignant_cells',
                     '3'='B_cells',
                     '4'='T_cells',
                     '5'='Myeloid_cells',
                     '6'='Fibroblasts',
                     '7'= 'unknown',
                     '8'='NK_cells',
                     '9'='Endothelial_cells',
                     '10'='unknown'
)

seu <- RenameIdents(seu, new.cluster.ids)
seu$annotation <- Idents(seu)

seu <- subset(seu, annotation != 'unknown')
seu <- seu %>% 
  RunUMAP(reduction = "harmony", dims = 1:20, verbose=F) 
```

```{r fig.height=4, fig.width=12}
plot_grid(DimPlot(seu, cols = my_colors) +
  ggtitle("Annotation"),

DimPlot(seu, group.by = 'age', cols = c("#6495EDFF", "#FF69B4FF")) +
  ggtitle("Age"), nrow = 1, rel_widths = c(1, 0.8))
```

```{r}
qsave(seu, paste0(PREPRDATADIR, 'seu_mouse_neutrophils.qs'))
```

```{r fig.height=5, fig.width=14}
Idents(seu) <- 'annotation'
markers <- FindAllMarkers(seu, only.pos = T, min.pct = 0.25)
top5 <- markers %>%
  dplyr::filter(!grepl("^Gm[0-9]", rownames(.))) %>% 
  dplyr::filter(!grepl("Rik$", rownames(.))) %>% 
  dplyr::filter(p_val_adj < 0.05) %>% 
  group_by(cluster) %>%
  top_n(n = 7, wt = avg_log2FC)

DotPlot(seu, top5$gene, cols = c('lightgrey', "#BA55D3FF")) +
  RotatedAxis()
```

# Overview

```{r}
convert_human_to_mouse <- function(gene_list) {
    output = c()
    mouse_human_genes = read.csv("https://www.informatics.jax.org/downloads/reports/HOM_MouseHumanSequence.rpt",sep="\t")

    for(gene in gene_list) {
          class_key = (mouse_human_genes %>% filter(Symbol == gene & Common.Organism.Name == "human"))[['DB.Class.Key']]
          if( !identical(class_key, integer(0)) ) {
            human_genes = (mouse_human_genes %>% filter(DB.Class.Key == class_key & Common.Organism.Name=="mouse, laboratory"))[,"Symbol"]
            for(human_gene in human_genes) {
                output = rbind(c(gene, human_gene), output)
            }
          }
     }
     return (output)
}
```

```{r fig.height=4, fig.width=13}
s.genes <- convert_human_to_mouse(cc.genes$s.genes)[,2]
g2m.genes <- convert_human_to_mouse(cc.genes$g2m.genes)[,2]
seu <- CellCycleScoring(seu, s.features = s.genes, g2m.features = g2m.genes)

plot_grid(dittoBarPlot(seu, 'age', group.by = 'annotation', color.panel = my_colors),
          dittoBarPlot(seu, 'Phase', group.by = 'annotation', color.panel = my_colors),
          dittoBarPlot(seu, 'annotation', group.by = 'age', color.panel = my_colors),
          nrow = 1, rel_widths = c(1, 1, 0.7))
```

# Analysis

```{r fig.height=8, fig.width=20}
Idents(seu) <- "age"
t_cells.de.markers <- FindMarkers(subset(seu, annotation %in% c('T_cells', 'NK_cells')), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  min.pct = 0.25)

b_cells.de.markers <- FindMarkers(subset(seu, annotation == 'B_cells'), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  min.pct = 0.25)

myeloid.de.markers <- FindMarkers(subset(seu, annotation == 'Myeloid_cells'), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  min.pct = 0.25)

malignant.de.markers <- FindMarkers(subset(seu, annotation == 'Malignant_cells'), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  min.pct = 0.25)
endo.de.markers <- FindMarkers(subset(seu, annotation == 'Endothelial_cells'), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  min.pct = 0.25)

stromal.de.markers <- FindMarkers(subset(seu, annotation == 'Fibroblasts'), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  min.pct = 0.25)

volcano_plot <- function(de.markers) {
  EnhancedVolcano(de.markers,
    lab = rownames(de.markers),
    x = 'avg_log2FC',
    y = 'p_val_adj',
    col = c("grey30","#8FBC8BFF", "#6495EDFF", "#BA55D3FF"),
    drawConnectors = TRUE,
    pCutoff = 0.05, 
    FCcutoff = 0.5,
    max.overlaps = 30
    ) +
  labs(subtitle = "Young vs Adult")
}

plot_grid(volcano_plot(t_cells.de.markers[!grepl("^Hb[ab]", rownames(t_cells.de.markers)), ]) +
            ggtitle('T cells + NK cells'),
          volcano_plot(b_cells.de.markers[!grepl("^Hb[ab]", rownames(b_cells.de.markers)), ]) +
            ggtitle('B cells'),
          volcano_plot(myeloid.de.markers[!grepl("^Hb[ab]", rownames(myeloid.de.markers)), ]) +
            ggtitle('Myeloid cells'),
          volcano_plot(malignant.de.markers[!grepl("^Hb[ab]", rownames(malignant.de.markers)), ]) +
            ggtitle('Malignant cells'),
          nrow = 1)
```


```{r eval=FALSE, include=FALSE}
prepare_de_results <- function(df, celltype) {
  df <- df %>%
    mutate(gene = rownames(df), celltype = celltype)
  rownames(df) <- NULL # Remove row names
  return(df)
}

# Apply the function to each DE result
t_cells.de.markers <- prepare_de_results(t_cells.de.markers, "T_cells")
b_cells.de.markers <- prepare_de_results(b_cells.de.markers, "B_cells")
myeloid.de.markers <- prepare_de_results(myeloid.de.markers, "Myeloid_cells")
malignant.de.markers <- prepare_de_results(malignant.de.markers, "Malignant_cells")
endo.de.markers <- prepare_de_results(endo.de.markers, "Endothelial_cells")
stromal.de.markers <- prepare_de_results(stromal.de.markers, "Stromal_cells")

# Combine all dataframes into one
all_de_markers <- bind_rows(
  t_cells.de.markers,
  b_cells.de.markers,
  myeloid.de.markers,
  malignant.de.markers,
  endo.de.markers,
  stromal.de.markers
)

qsave(all_de_markers, paste0(PREPRDATADIR, 'DEG_sc_mouse.qs'))
```

# Scatter plots

```{r echo=FALSE, fig.height=7, fig.width=7}
seu$celltype.age <- paste(seu$annotation, seu$age, sep = "_")
Idents(seu) <- "celltype.age"
seu_bulk <- AggregateExpression(seu, group.by = c("annotation", "age"), return.seurat = TRUE)

p1 <- CellScatter(seu_bulk, "T-cells_young", "T-cells_adult")
p1 <- CellScatter(seu_bulk, "T-cells_young", "T-cells_adult", highlight = p1$data %>% filter(abs(T.cells_adult - T.cells_young) > 1) %>% rownames())
p1 <- LabelPoints(plot = p1, points = p1$data %>% filter(abs(T.cells_adult - T.cells_young) > 1) %>% rownames(), repel = TRUE)

p2 <- CellScatter(seu_bulk, "B-cells_young", "B-cells_adult")
p2 <- CellScatter(seu_bulk, "B-cells_young", "B-cells_adult", highlight = p2$data %>% filter(abs(B.cells_adult - B.cells_young) > 1) %>% rownames())
p2 <- LabelPoints(plot = p2, points = p2$data %>% filter(abs(B.cells_adult - B.cells_young) > 1) %>% rownames(), repel = TRUE)

p3 <- CellScatter(seu_bulk, "Myeloid-cells_young", "Myeloid-cells_adult")
p3 <- CellScatter(seu_bulk, "Myeloid-cells_young", "Myeloid-cells_adult", highlight = p3$data %>% filter(abs(Myeloid.cells_adult - Myeloid.cells_young) > 1) %>% rownames())
p3 <- LabelPoints(plot = p3, points = p3$data %>% filter(abs(Myeloid.cells_adult - Myeloid.cells_young) > 1) %>% rownames(), repel = TRUE)

p4 <- CellScatter(seu_bulk, "Malignant-cells_young", "Malignant-cells_adult")
p4 <- CellScatter(seu_bulk, "Malignant-cells_young", "Malignant-cells_adult", highlight = p4$data %>% filter(abs(Malignant.cells_adult - Malignant.cells_young) > 1) %>% rownames())
p4 <- LabelPoints(plot = p4, points =  p4$data %>% filter(abs(Malignant.cells_adult - Malignant.cells_young) > 1) %>% rownames(), repel = TRUE)

p1 + p2 + p3 + p4
```

```{r eval=FALSE, include=FALSE}
p3$data %>% 
  dplyr::filter(colors != 'Unselected')
```


```{r eval=FALSE, include=FALSE}
t_cells.de.markers %>% dplyr::filter(p_val_adj < 0.05 & abs(avg_log2FC) >= 0.5 )

b_cells.de.markers %>% dplyr::filter(p_val_adj < 0.05 & abs(avg_log2FC) >= 0.5 )

myeloid.de.markers %>% dplyr::filter(p_val_adj < 0.05 & abs(avg_log2FC) >= 0.5 )

malignant.de.markers %>% dplyr::filter(p_val_adj < 0.05 & abs(avg_log2FC) >= 0.5 )

```

# Pseudobulk DE

```{r create pseudoreplicates, include=FALSE}
seu$rep <- NA
create_pseudorep <- function(seu) {
  
  rep1 <- c()
  rep2 <- c()
  rep3 <- c()
  reps <- list(rep1, rep2, rep3)
  
  samples <- seu$age %>% unique
  cell_types <- seu$annotation %>% unique
  sample_annot_table <- table(seu$annotation, seu$age)
  for (sample in samples) {
    for (celltype in cell_types) {
      
      if (sample_annot_table[celltype, sample] >= 150) {
        
        cells <- WhichCells(seu, expression = annotation ==  celltype & age == sample)
        cells_split <- split(cells,  cut(seq_along(cells), 3, labels = FALSE))
        reps[[1]] <- c(reps[[1]], cells_split[1])
        reps[[2]] <- c(reps[[2]], cells_split[2])
        reps[[3]] <- c(reps[[3]], cells_split[3])
      }
      else if (sample_annot_table[celltype, sample] >= 90) {
        cells <- WhichCells(seu, expression = annotation ==  celltype & age == sample)
        cells_split <- split(cells,  cut(seq_along(cells), 2, labels = FALSE))
        reps[[1]] <- c(reps[[1]], cells_split[1])
        reps[[2]] <- c(reps[[2]], cells_split[2])
      }
    }
  }
  return(reps)
}

replicates_list <- create_pseudorep(seu)

for (i in seq_along(replicates_list)) {
  replicate_name <- paste0("rep", i)
  cells <- unlist(replicates_list[[i]])
  seu$rep[cells] <- replicate_name
}
```

```{r}
seu_bulk <- subset(seu, rep %in% c('rep1', 'rep2', 'rep3'))
seu_bulk <- AggregateExpression(seu_bulk, return.seurat = T, slot = "counts", assays = "RNA", 
                            group.by = c("annotation", "age", 'rep'))
```


```{r fig.height=8, fig.width=20}
Idents(seu_bulk) <- "age"
t_cells.de.markers <- FindMarkers(subset(seu_bulk, annotation == 'T cells'), 
                                  ident.1 = "young", ident.2 = "adult", 
                                  slot = "counts",
                                  test.use = "DESeq2", verbose = F)

b_cells.de.markers <- FindMarkers(subset(seu_bulk, annotation == 'B cells'), 
                                  ident.1 = "young", ident.2 = "adult", slot = "counts",
                                  test.use = "DESeq2", verbose = F, 
                                  min.cells.group = 2)

myeloid.de.markers <- FindMarkers(subset(seu_bulk, annotation == 'Myeloid cells'), 
                                  ident.1 = "young", ident.2 = "adult", slot = "counts",
                                  test.use = "DESeq2", verbose = F)

malignant.de.markers <- FindMarkers(subset(seu_bulk, annotation == 'Malignant cells'), 
                                  ident.1 = "young", ident.2 = "adult", slot = "counts",
                                  test.use = "DESeq2", verbose = F)

plot_grid(volcano_plot(t_cells.de.markers) +
            ggtitle('T-cells'),
          volcano_plot(b_cells.de.markers) +
            ggtitle('B-cells'),
          volcano_plot(myeloid.de.markers) +
            ggtitle('Myeloid cells'),
          volcano_plot(malignant.de.markers) +
            ggtitle('Malignant cells'),
          nrow = 1)
```

# Heatmap

```{r eval=FALSE, fig.height=14, fig.width=12, include=FALSE}
heatmap_tcells <- dittoHeatmap(subset(seu, annotation == 'T_cells'), t_cells.de.markers %>% 
                            filter(p_val_adj < 0.05 & abs(avg_log2FC) > 1) %>% 
                            dplyr::arrange(desc(avg_log2FC)) %>% 
                            rownames(),
             order.by = 'age', annot.by = 'age', silent=T,
             annot.colors = c("#87CEEBFF", "#DDA0DDFF"), 
             main = 'T cells', 
             breaks=seq(-2, 2, 0.2), heatmap.colors = colorRampPalette(c("#6495EDFF", "white", "#FF69B4FF"))(length(seq(-2, 2, 0.2))))

heatmap_bcells <- dittoHeatmap(subset(seu, annotation == 'B_cells'), b_cells.de.markers %>% 
                            filter(p_val_adj < 0.05 & abs(avg_log2FC) > 0.5) %>% 
                            dplyr::arrange(desc(avg_log2FC)) %>% 
                            rownames(),
             order.by = 'age', annot.by = 'age', silent=T,
             annot.colors = c("#87CEEBFF", "#DDA0DDFF"), 
             main = 'B cells', 
             breaks=seq(-2, 2, 0.2), heatmap.colors = colorRampPalette(c("#6495EDFF", "white", "#FF69B4FF"))(length(seq(-2, 2, 0.2))))

heatmap_myelcells <- dittoHeatmap(subset(seu, annotation == 'Myeloid_cells'), myeloid.de.markers %>% 
                            filter(p_val_adj < 0.05 & abs(avg_log2FC) > 0.8) %>% 
                            dplyr::arrange(desc(avg_log2FC)) %>% 
                            rownames(),
             order.by = 'age', annot.by = 'age', silent=T,
             annot.colors = c("#87CEEBFF", "#DDA0DDFF"), 
             main = 'Myeloid cells', 
             breaks=seq(-2, 2, 0.2), heatmap.colors = colorRampPalette(c("#6495EDFF", "white", "#FF69B4FF"))(length(seq(-2, 2, 0.2))))

heatmap_maligcells <- dittoHeatmap(subset(seu, annotation == 'Malignant_cells'), malignant.de.markers %>% 
                            filter(p_val_adj < 0.05 & abs(avg_log2FC) > 0.5) %>% 
                            dplyr::arrange(desc(avg_log2FC)) %>% 
                            rownames(),
             order.by = 'age', annot.by = 'age', silent=T,
             annot.colors = c("#87CEEBFF", "#DDA0DDFF"), 
             main = 'Malignant cells', 
             breaks=seq(-2, 2, 0.2), heatmap.colors = colorRampPalette(c("#6495EDFF", "white", "#FF69B4FF"))(length(seq(-2, 2, 0.2))))

plot_grid(heatmap_bcells[[4]], heatmap_maligcells[[4]], nrow=1)
```

```{r eval=FALSE, fig.height=20, fig.width=12, include=FALSE}
plot_grid(heatmap_tcells[[4]], heatmap_myelcells[[4]], nrow=1)
```

# Myeloid cells analysis

```{r include=FALSE}
myeloid <- subset(seu, annotation == 'Myeloid_cells')
myeloid <- CellCycleScoring(myeloid, s.features = s.genes, g2m.features = g2m.genes)
```

```{r include=FALSE}
myeloid <- myeloid %>% 
    NormalizeData() %>%
    FindVariableFeatures()%>%
    ScaleData() %>%
    RunPCA()

myeloid <- myeloid %>% 
    RunUMAP(dims = 1:8) %>%
    FindNeighbors(dims = 1:8) %>%
    FindClusters(resolution = seq(0.1, 1, 0.1))
```

```{r eval=FALSE, fig.height=20, fig.width=10, include=FALSE}
DimHeatmap(myeloid, dims = 1:20)
```

```{r eval=FALSE, include=FALSE}
ElbowPlot(myeloid)
```

```{r include=FALSE}
DimPlot(myeloid, group.by = 'RNA_snn_res.0.3')
DimPlot(myeloid, group.by = 'Phase')
DimPlot(myeloid, group.by = 'age')
FeaturePlot(myeloid, 'percent.mt')
FeaturePlot(myeloid, 'complexity')
clustree(myeloid)
```


## SingleR annotation

```{r fig.height=5, fig.width=8, include=FALSE}
sce <- as.SingleCellExperiment(myeloid)
colLabels(sce) <- myeloid$RNA_snn_res.1

# #cluster-wise annotation
pred_bped_main <- SingleR(test = sce, ref = mouse_ref_imm, clusters=colLabels(sce),
                          labels = mouse_ref_imm$label.fine, BPPARAM=MulticoreParam(5))
# # Create a named vector for RenameIdents
pred_bped_main$pruned.labels <- gsub(" \\(.*\\)", "", pred_bped_main$pruned.labels)
singleR_labels <- pred_bped_main$pruned.labels
names(singleR_labels) <- rownames(pred_bped_main)

Idents(myeloid) <-  'RNA_snn_res.1'
# Update cluster identities in Seurat object based on SingleR results
myeloid <- RenameIdents(myeloid, singleR_labels)
myeloid[['annotation']] <- Idents(myeloid)
```

```{r fig.height=5, fig.width=8}
DimPlot(myeloid, group.by = 'annotation', cols = my_colors) + ggtitle('Annotation')
```

```{r echo=FALSE, fig.height=4, fig.width=10}
Idents(myeloid) <- 'annotation'
markers <- FindAllMarkers(myeloid, only.pos = T, min.pct = 0.25)
top5 <- markers %>%
  dplyr::filter(!grepl("^Gm[0-9]", rownames(.))) %>% 
  dplyr::filter(!grepl("Rik$", rownames(.))) %>% 
  dplyr::filter(p_val_adj < 0.05) %>% 
  group_by(cluster) %>%
  top_n(n = 7, wt = avg_log2FC)

DotPlot(myeloid, top5$gene, cols = c('lightgrey', "#BA55D3FF")) +
  RotatedAxis()
```

```{r fig.height=8, fig.width=8}
granulocyte_markers <- c("Lyz2", "S100a8", "S100a9", "Csf3r", "Itgam")
FeaturePlot(myeloid, granulocyte_markers)
```

```{r fig.height=4, fig.width=13}
plot_grid(dittoBarPlot(myeloid, 'age', group.by = 'annotation', color.panel = my_colors) + ggtitle('Age'),
          dittoBarPlot(myeloid, 'age', group.by = 'annotation', color.panel = my_colors, scale = 'count') + ggtitle('Age'),
          dittoBarPlot(myeloid, 'annotation', group.by = 'age', color.panel = my_colors) + ggtitle('Annotation'),
          nrow = 1, rel_widths = c(1, 1, 0.7))
```

```{r}
table(myeloid$annotation, myeloid$age)
```
# Neutrophils analysis

```{r}
myeloid$celltype.age <- paste(myeloid$annotation, myeloid$age, sep = "_")
Idents(myeloid) <- "celltype.age"
myeloid_bulk <- AggregateExpression(myeloid, group.by = c("annotation", "age"), return.seurat = TRUE)

p1 <- CellScatter(myeloid_bulk, "Neutrophils_young", "Neutrophils_adult")
p1 <- CellScatter(myeloid_bulk, "Neutrophils_young", "Neutrophils_adult", highlight = p1$data %>% filter(abs(Neutrophils_adult - Neutrophils_young) > 1) %>% rownames())
p1 <- LabelPoints(plot = p1, points = p1$data %>% filter(abs(Neutrophils_adult - Neutrophils_young) > 1) %>% rownames(), repel = TRUE)

p1
```

## lfc top

```{r fig.height=4, fig.width=14}
neutrophils_markers <- FindMarkers(myeloid, ident.1 = 'Neutrophils_young', ident.2 = 'Neutrophils_adult')

top10 <- neutrophils_markers %>%
  dplyr::filter(!grepl("^Gm[0-9]", rownames(.))) %>% 
  dplyr::filter(!grepl("Rik$", rownames(.))) %>% 
  dplyr::filter(p_val < 0.05) %>% 
  top_n(n = 10, wt = avg_log2FC) %>% 
  rbind(neutrophils_markers %>%
  dplyr::filter(!grepl("^Gm[0-9]", rownames(.))) %>% 
  dplyr::filter(!grepl("Rik$", rownames(.))) %>% 
  dplyr::filter(p_val < 0.05) %>% 
  top_n(n = 10, wt = -avg_log2FC))

DotPlot(subset(myeloid, annotation == 'Neutrophils'), scale = F, rownames(top10), cols = c('lightgrey', "#BA55D3FF")) +
  RotatedAxis()
```

## pval top

```{r fig.height=4, fig.width=14}
top10 <- neutrophils_markers %>%
  dplyr::filter(avg_log2FC > 0) %>% 
  dplyr::filter(!grepl("^Gm[0-9]", rownames(.))) %>% 
  dplyr::filter(!grepl("Rik$", rownames(.))) %>% 
  dplyr::filter(p_val < 0.05) %>% 
  top_n(n = -10, wt = p_val) %>% 
  rbind(neutrophils_markers %>%
  dplyr::filter(avg_log2FC < 0) %>% 
  dplyr::filter(!grepl("^Gm[0-9]", rownames(.))) %>% 
  dplyr::filter(!grepl("Rik$", rownames(.))) %>% 
  dplyr::filter(p_val < 0.05) %>% 
  top_n(n = -10, wt = p_val))

DotPlot(subset(myeloid, annotation == 'Neutrophils'), scale = F, rownames(top10), cols = c('lightgrey', "#BA55D3FF")) +
  RotatedAxis()
```

```{r}
VlnPlot(myeloid, features = c('S100a9', 'S100a8'), group.by = 'annotation', split.by = 'age', split.plot = T, cols = my_colors)
```

```{r}
VlnPlot(myeloid, features = c('S100a9', 'S100a8'), group.by = 'annotation', split.by = 'age', split.plot = T, cols = my_colors, layer = 'counts')
```

## All cell types

```{r}
VlnPlot(seu, features = 'S100a9', group.by = 'annotation', split.by = 'age', split.plot = T, cols = my_colors)
```

```{r}
FeaturePlot(seu, c('S100a9', 'S100a8'))
```


## Targets of calprotectin

```{r}
mouse_genes <- c(
  "Bcl2", "Mapk1", "Bax", "Nfkb1", "Jun", "Tnf", "Il6", "Ap1", "Cxcl1", "Ccl5", "Ccl7", 
  "Slc39a10", "Lcn2", "Zc3h12a", "Enpp2", "Mmp10", "Mmp1", "Mmp2", "Mmp9", 
  "Pik3ca", "Rac1",
  "Casp1", "Casp3", "Casp4", "Casp5", "Casp7", "Casp8", "Casp9", "Casp10", "Casp14",
  "Xaf1", "Ulk1", "Xiap", "H2afx", "Trp53bp1", "Atg13", "Rb1cc1", "Ambra1", "Becn1", 
  "Pik3c3", "Atg14", "Uvrag", "Atg5", "Atg12", "Atg16l1", "Map1lc3a", "Atg7", "Atg3", 
  "Atg10", "Rab7a", "Lamp1", "Lamp2", "Stx17", "Mtor", "Prkaa1", "Tfeb", "Bak1", 
  "Bnip3", "Bbc3", "Pmaip1", "Fas", "Mcl1", "Birc5", "Dnm1l", "Vdac1", "Mptp", 
  "Tfam", "Atp5f1a", "Tnfrsf1a", "Ddit3", "Atf4", "Tlr4", "Ager", "P2rx7", "Nlrp3", 
  "Capn1", "Nfe2l2", "Cycs", "Gsk3b", "Il18", "Aifm1", "Nox1", "Nox2", "Nox3", "Nox4", "Nox5", 
  "Sod1", "Sod2", "Sod3", "Cat", "Gpx1", "Gpx4", "Txn", "Txnrd1", "Prdx1", "Prdx2", "Prdx3", 
  "Xdh", "Ahr", 
  # Fibroblast related
  "Vim", "Stat3", "Smad2", "Smad3", "Il33", "Il1b", "Acta2", "Cxcl8", "Col1a1", "Pdgfb",
  # Macrophage related
  "Arg1", "P2rx7", "Socs3", "Nlrp3", "Myd88", "Nos2"
)
```


```{r fig.height=20, fig.width=20}
VlnPlot(mouse, features = c('Atg12', 'Myd88', 'Uvrag'), group.by = 'annotation', split.by = 'age', split.plot = T, cols = my_colors)
```

