---
title: "t_cells_mouse_subtypes"
author: "Kate Petrenko"
date: "2024-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(data.table)
library(Seurat)
library(scDblFinder)
library(DoubletFinder)
library(dplyr)
library(remotes)
# remotes::install_github("carmonalab/STACAS")
library(STACAS)
library(SingleR)
# install.packages("scGate")
library(scGate)
library(ggplot2)
library(BiocParallel)
library(harmony)
library(RColorBrewer)
library(stringr)
library(cowplot)
library(scuttle)
# install.packages("devtools")
# BiocManager::install("Homo.sapiens")
# BiocManager::install("jpmam1/scalop") #forked copy of a really good guy 
# devtools::install_github("jlaffy/infercna")
library(infercna)
# library(infercnv)
library(parallel)
library(future)
library(clustree)
library(dittoSeq)
# install.packages("ggh4x")
library(ggh4x)
#BiocManager::install('EnhancedVolcano')
library(EnhancedVolcano)
library(clusterProfiler)
# BiocManager::install('org.Mm.eg.db')
library("org.Mm.eg.db")
library(ReactomePA)
library(msigdbr)
# install.packages('qs')
library(qs)
# devtools::install_github("ncborcherding/escape")
# devtools::install_github("rcastelo/GSVA")
library(escape)
# install.packages('gprofiler2')
library(gprofiler2)
# remotes::install_github("carmonalab/ProjecTILs")
library(ProjecTILs)
library(gridExtra)
```

```{r global variables, include=FALSE}
set.seed(100)
DATADIR = '~/Desktop/lab/neuroblastoma/data/'
WORKDIR = '~/Desktop/lab/neuroblastoma/neuroblastoma/'
PREPRDATADIR = '~/Desktop/lab/neuroblastoma/data/'

my_colors <- c("#9ACD32FF", "#4682B4FF",  "#DDA0DDFF", "#FFA07AFF", "#8FBC8BFF",
               "#40E0D0FF",  "#F0E68CFF", "#5F9EA0FF", "#D2B48CFF",  
               "#6495EDFF", "#FF69B4FF", "#BA55D3FF",  "#F08080FF", "#32CD32FF",  
               "#FFDAB9FF",  "#87CEEBFF")
```

# T-cells subtypes

```{r}
t_cells <- qread(paste0(PREPRDATADIR, 't_cells_mouse_ssGSEAs3.qs'))
```

```{r echo=FALSE, fig.height=5, fig.width=12}
plot_grid(DimPlot(t_cells, group.by = 'Annotation', cols = my_colors) +
  ggtitle("Annotation"), 
  DimPlot(t_cells, group.by = 'age', cols = c("#6495EDFF", "#FF69B4FF")) +
  ggtitle("Age"),
  nrow = 1, rel_widths = c(1.2, 1))
```

```{r fig.height=4, fig.width=5}
Idents(t_cells) <- t_cells$RNA_snn_res.0.2
DimPlot(t_cells, cols = my_colors) +
  ggtitle("Clusters")
```

## Th1 

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Cd4', 'Cd8a', 'Ifng', 'Il2', 'Tnf', 'Stat1', 'Stat4', 'Tbx21', 'Il12rb2', 'Il27ra', 'Il18r1', 'Ccr5', 'Cxcr3'))
```

```{r fig.height=10, fig.width=12}
FeaturePlot(t_cells, c('Cd4', 'Cd8a', 'Ifng', 'Il2', 'Tnf', 'Stat1', 'Stat4', 'Tbx21', 'Il12rb2', 'Il27ra', 'Il18r1', 'Ccr5', 'Cxcr3'))
```


## Th2

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Cd4', 'Cd8a', 'Ccr3', 'Ccr4', 'Ccr8', 'Cxcr4', 'Il1rl1', 'Stat5a', 'Stat5b', 'Stat6', 'Gata3', 'Il4', 'Il5', 'Il9', 'Il13', 'Il25'))
```

```{r fig.height=10, fig.width=12}
FeaturePlot(t_cells, c('Cd4', 'Cd8a', 'Ccr3', 'Ccr4', 'Ccr8', 'Cxcr4', 'Il1rl1', 'Stat5a', 'Stat5b', 'Stat6', 'Gata3', 'Il4', 'Il5', 'Il9', 'Il13', 'Il25'))
```

## Th9

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Spi1', 'Irf4', 'Il9', 'Ccl17', 'Ccl22', 'Il10'))
```

```{r fig.height=10, fig.width=12}
FeaturePlot(t_cells, c('Spi1', 'Irf4', 'Il9', 'Ccl17', 'Ccl22', 'Il10'))
```

## Th17

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Tgfb1', 'Tgfb2', 'Il6ra', 'Il21r', 'Il23r', 'Stat3', 'Rorc', 'Il17a', 'Il17f', 'Il21', 'Il22'))
```

```{r fig.height=10, fig.width=12}
FeaturePlot(t_cells, c('Tgfb1', 'Tgfb2', 'Il6ra', 'Il21r', 'Il23r', 'Stat3', 'Rorc', 'Il17a', 'Il17f', 'Il21', 'Il22'))
```


# SingleR annotation

I used [ImmGen reference](https://www.immgen.org/) for the annotation.

```{r}
mouse_ref_imm <- celldex::ImmGenData()
t_cells <- t_cells %>% 
    FindClusters(resolution = 1.5)
  
sce <- as.SingleCellExperiment(t_cells)
colLabels(sce) <- t_cells$RNA_snn_res.1.5
Idents(t_cells) <- 'RNA_snn_res.1.5'

# #cluster-wise annotation
pred_bped_main <- SingleR(test = sce, ref = mouse_ref_imm, clusters=colLabels(sce),
                          labels = mouse_ref_imm$label.fine, BPPARAM=MulticoreParam(5))
# # Create a named vector for RenameIdents
singleR_labels <- pred_bped_main$pruned.labels
names(singleR_labels) <- rownames(pred_bped_main)

# Update cluster identities in Seurat object based on SingleR results
t_cells <- RenameIdents(t_cells, singleR_labels)
t_cells[['SingleR_imm_ref']] <- Idents(t_cells)

DimPlot(t_cells, group.by = 'SingleR_imm_ref', cols = my_colors)
```

# Markers 

```{r fig.height=6, fig.width=12}
Idents(t_cells) <- t_cells$RNA_snn_res.0.2
tcells.clusters.markers <- FindAllMarkers(t_cells, only.pos = TRUE, min.pct = 0.25)
top5 <- tcells.clusters.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>% 
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC)

DotPlot(t_cells, top5$gene, cols = c('lightgrey', "#BA55D3FF")) +
  RotatedAxis()
```


# Cell-cycle score

```{r}
mmus_s = gorth(cc.genes$s.genes, source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name
mmus_g2m = gorth(cc.genes$g2m.genes, source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name

t_cells <- CellCycleScoring(t_cells, s.features = mmus_s, g2m.features = mmus_g2m)

DimPlot(t_cells, group.by = 'Phase')
```

```{r include=FALSE}
t_cells <- t_cells %>% 
  ScaleData(vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(t_cells)) %>% 
  RunPCA(verbose=FALSE) %>% 
  RunHarmony(., 'age',
             lambda = 1, verbose = FALSE) 

t_cells <- t_cells %>% 
  RunUMAP(reduction = "harmony", dims = 1:10, verbose=F) %>% 
  FindNeighbors(dims = 1:6) %>%
  FindClusters(resolution = seq(0.1, 1, 0.1))

clustree(t_cells)
```

```{r eval=FALSE, fig.height=20, fig.width=12, include=FALSE}
DimHeatmap(t_cells, dims = 1:20)
```

```{r eval=FALSE, include=FALSE}
ElbowPlot(t_cells)
```

```{r}
DimPlot(t_cells, group.by = 'RNA_snn_res.0.3', cols = my_colors)
DimPlot(t_cells, group.by = 'Phase', cols = my_colors)
```

## Markers 

```{r fig.height=6, fig.width=12}
Idents(t_cells) <- 'RNA_snn_res.1.5'
tcells.clusters.markers <- FindAllMarkers(t_cells, only.pos = TRUE, min.pct = 0.25)
top5 <- tcells.clusters.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>% 
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC)

DotPlot(t_cells, top5$gene %>% unique(), cols = c('lightgrey', "#BA55D3FF")) +
  RotatedAxis()
```

## SingleR

```{r fig.width=10}
sce <- as.SingleCellExperiment(t_cells)
colLabels(sce) <- t_cells$RNA_snn_res.1

# #cluster-wise annotation
pred_bped_main <- SingleR(test = sce, ref = mouse_ref_imm, clusters=colLabels(sce),
                          labels = mouse_ref_imm$label.fine, BPPARAM=MulticoreParam(5))
# # Create a named vector for RenameIdents
singleR_labels <- pred_bped_main$pruned.labels
names(singleR_labels) <- rownames(pred_bped_main)

# Update cluster identities in Seurat object based on SingleR results
t_cells <- RenameIdents(t_cells, singleR_labels)
t_cells[['SingleR_imm_ref_v2']] <- Idents(t_cells)

DimPlot(t_cells, group.by = 'SingleR_imm_ref_v2', cols = my_colors)
```

```{r eval=FALSE, fig.height=5, fig.width=12, include=FALSE}
Idents(object = t_cells) <- "RNA_snn_res.0.3"

new.cluster.ids <- c('0'=NA,
                     '1'=NA,
                     '2'=NA,
                     '3'='NK_cells',
                     '4'=NA
)

t_cells <- RenameIdents(t_cells, new.cluster.ids)
t_cells$NK_annotation <- Idents(t_cells)
```

```{r fig.height=10, fig.width=10}
Idents(t_cells) <- t_cells$RNA_snn_res.1.5
VlnPlot(t_cells, c('Cd3e', 'Cd3d', 'Cd3g', 'Klrb1c', 'Ncr1', 'Klrk1', 'Cd4', 'Cd8a', 'Cd8b1',
                   'Tbx21', 'Cxcr3', 'Il2ra', 'Entpd1', 'Foxp3','Ctla4'))
```

```{r}
FeaturePlot(t_cells, c('Hbb-bs', 'Hbb-bt', 'Hba-a1', 'Hba-a2'))
FeaturePlot(t_cells, c('percent.mt', 'complexity'))
```


## Treg

```{r fig.height=12, fig.width=16}
FeaturePlot(t_cells, c('Cd4', 'Cd8b1', 'Il17a', 'Il17f', 'Rora', 'Maf', 'Ctla4', 'Rorc', 'Foxp3', 'Il12a', 'Il10'))
```

## Memory

```{r fig.height=8, fig.width=10}
FeaturePlot(t_cells, c('Il7r', 'Sell', 'Cd44', 'Ccr7'))
```

## Th1 

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Cd4', 'Cd8a', 'Ifng', 'Il2', 'Tnf', 'Stat1', 'Stat4', 'Tbx21', 'Il12rb2', 'Il27ra', 'Il18r1', 'Ccr5', 'Cxcr3'))
```


## Th2

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Cd4', 'Cd8a', 'Ccr3', 'Ccr4', 'Ccr8', 'Cxcr4', 'Il1rl1', 'Stat5a', 'Stat5b', 'Stat6', 'Gata3', 'Il4', 'Il5', 'Il9', 'Il13', 'Il25'))
```

## Th9

```{r fig.height=10, fig.width=10}
VlnPlot(t_cells, c('Spi1', 'Irf4', 'Il9', 'Ccl17', 'Ccl22', 'Il10'))
```

## Th17

```{r fig.height=8, fig.width=10}
VlnPlot(t_cells, c('Tgfb1', 'Tgfb2', 'Il6ra', 'Il21r', 'Il23r', 'Stat3', 'Rorc', 'Il17a', 'Il17f', 'Il21', 'Il22'))
```


# Articles

## 2

```{r fig.height=10, fig.width=10}
Idents(t_cells) <- t_cells$RNA_snn_res.0.2
VlnPlot(t_cells, c('Tcf7', 'Ccr7', 'Cd2', 'Pdcd1', 'Tnfrsf9', 'Tnfrsf4', 'Ctla4', 'Ifngr1', 'Fasl'))
```

```{r fig.height=10, fig.width=12}
FeaturePlot(t_cells, c('Tcf7', 'Ccr7', 'Cd2', 'Pdcd1', 'Tnfrsf9', 'Tnfrsf4', 'Ctla4', 'Ifngr1', 'Fasl'))
```

# ProjectTILs

```{r}
library(ProjecTILs)
ref <- load.reference.map()
data(query_example_seurat)

query.projected <- Run.ProjecTILs(query_example_seurat, ref=ref)

querydata <- ProjecTILs.classifier(query = t_cells, ref = ref)
DimPlot(querydata, group.by = "functional.cluster", cols = my_colors)
```

```{r}
querydata <- Run.ProjecTILs(querydata, ref = ref, split.by = "age", ncores = 4)
plot.projection(ref, querydata, linesize = 0.5, pointsize = 0.5)
```

```{r fig.height=9, fig.width=12}
query.list <- SplitObject(querydata, split.by = "age")
plot.states.radar(ref, query = query.list, min.cells = 10, genes4radar = c("Foxp3",
    "Cd4", "Cd8a", "Tcf7", "Ccr7", "Gzmb", "Pdcd1", "Havcr2", "Tox", "Entpd1", "Cxcr5",
    "Ifng", "Cxcl13", "Xcl1", "Itgae"))
```

```{r}
# Step 1: Combine 'young' cluster information
young_cluster_info <- query.list[["young"]]$functional.cluster
young_metadata_vector <- as.character(young_cluster_info)
names(young_metadata_vector) <- names(young_cluster_info)

# Initialize the vector with NA for all cells
projection_annotation <- rep(NA, length(Cells(t_cells)))
names(projection_annotation) <- Cells(t_cells)

# Assign 'young' annotations
projection_annotation[names(young_metadata_vector)] <- young_metadata_vector

# Step 2: Combine 'adult' cluster information
adult_cluster_info <- query.list[["adult"]]$functional.cluster
adult_metadata_vector <- as.character(adult_cluster_info)
names(adult_metadata_vector) <- names(adult_cluster_info)

# Assign 'adult' annotations, keeping existing 'young' annotations where they exist
projection_annotation[names(adult_metadata_vector)] <- ifelse(
  is.na(projection_annotation[names(adult_metadata_vector)]),
  adult_metadata_vector,
  projection_annotation[names(adult_metadata_vector)]
)

# Step 3: Add NK annotation where projection_annotation is still NA
nk_annotation_vector <- t_cells$NK_annotation  # Assuming NK_annotation exists in t_cells

# Assign NK annotations where projection_annotation is NA
projection_annotation <- ifelse(
  is.na(projection_annotation) & !is.na(nk_annotation_vector),
  "NK_cells",
  projection_annotation
)

# Add the final combined annotation to the Seurat object
t_cells$projection_annotation <- factor(projection_annotation, levels = c("CD8_Tex", "CD8_Tpex", "CD8_EffectorMemory", "CD8_EarlyActiv", "CD8_NaiveLike", "CD4_NaiveLike", "Tfh", "Th1", "Treg", 'NK_cells'))
```

```{r fig.height=4, fig.width=13}

pll <- list()

pll[[1]] <- plot.projection(ref, query.list[["young"]], linesize = 0.5, pointsize = 0.5, cols  = my_colors) +
  scale_fill_discrete(type = my_colors, breaks=c("CD8_Tex", "CD8_Tpex", "CD8_EffectorMemory", "CD8_EarlyActiv", "CD8_NaiveLike", "CD4_NaiveLike", "Tfh", "Th1", "Treg")) +
    ggtitle("Young") + NoLegend()
# pll[[2]] <- plot.statepred.composition(ref, query.list[["young"]], metric = "Percent") +
#     ggtitle("Young") + ylim(0, 40)
# pll[[2]] <- dittoBarPlot(subset(t_cells, age == 'young'), group.by = 'projection_annotation', color.panel = my_colors) +
#    ggtitle("Young")
pll[[3]] <- plot.projection(ref, query.list[["adult"]], linesize = 0.5, pointsize = 0.5, cols = my_colors) +
  scale_fill_discrete(type = my_colors, breaks=c("CD8_Tex", "CD8_Tpex", "CD8_EffectorMemory", "CD8_EarlyActiv", "CD8_NaiveLike", "CD4_NaiveLike", "Tfh", "Th1", "Treg")) +
    ggtitle("Adult") 
# pll[[4]] <- plot.statepred.composition(ref, query.list[["adult"]], metric = "Percent") +
#     ggtitle("Adult") + ylim(0, 40)
# pll[[4]] <- dittoBarPlot(subset(t_cells, age == 'adult'),  group.by = 'projection_annotation', color.panel = my_colors) +
#    ggtitle("Adult")
pll[[5]] <- dittoBarPlot(t_cells, 'projection_annotation', group.by = 'age', color.panel = my_colors) +
  scale_fill_manual(values = my_colors, breaks=c("CD8_Tex", "CD8_Tpex", "CD8_EffectorMemory", "CD8_EarlyActiv", "CD8_NaiveLike", "CD4_NaiveLike", "Tfh", "Th1", "Treg", 'NK_cells')) +
  ggtitle('')

plot_grid(pll[[1]], pll[[3]], pll[[5]], ncol = 3, nrow = 1, rel_widths = c(1.3, 2, 1.2))


```


```{r}
which.types <- table(t_cells$projection_annotation) > 10
states_all <- c("CD8_Tex", "CD8_Tpex", "CD8_EffectorMemory", "CD8_EarlyActiv", "CD8_NaiveLike", "CD4_NaiveLike", "Tfh", "Th1", "Treg", 'NK_cells')
names(my_colors) <- states_all
cols_use <- my_colors[names(which.types)][which.types]

query.list <- SplitObject(t_cells, split.by = "age")

norm.c <- table(query.list[["adult"]]$projection_annotation)/sum(table(query.list[["adult"]]$projection_annotation))
norm.q <- table(query.list[["young"]]$projection_annotation)/sum(table(query.list[["young"]]$projection_annotation))

foldchange <- norm.q[which.types]/norm.c[which.types]
foldchange <- sort(foldchange, decreasing = T)

tb.m <- reshape2::melt(foldchange)
colnames(tb.m) <- c("Cell_state", "Fold_change")
pll <- list()
ggplot(tb.m, aes(x = Cell_state, y = Fold_change, fill = Cell_state)) + geom_bar(stat = "identity") +
    scale_fill_manual(values = cols_use) + geom_hline(yintercept = 1) + scale_y_continuous(trans = "log2") +
    ggtitle("Young vs. Adult") + theme_bw() + theme(axis.text.x = element_blank(),
    legend.position = "left")
```

```{r}
DimPlot(ref, group.by = "functional.cluster", cols = my_colors)
```

