---
title: "WGCNA_mouse"
author: "Kate Petrenko"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github('smorabit/hdWGCNA', ref='dev', force = T)
library(WGCNA)
library(hdWGCNA)
library(data.table)
library(Seurat)
library(scDblFinder)
library(DoubletFinder)
library(remotes)
# remotes::install_github("carmonalab/STACAS")
library(STACAS)
library(SingleR)
# install.packages("scGate")
library(scGate)
library(ggplot2)
library(BiocParallel)
# BiocManager::install("harmony")
library(harmony)
library(RColorBrewer)
library(stringr)
library(cowplot)
library(scuttle)
# install.packages("devtools")
# BiocManager::install("Homo.sapiens")
# BiocManager::install("jpmam1/scalop") #forked copy of a really good guy
# devtools::install_github("jlaffy/infercna")
library(infercna)
# library(infercnv)
library(parallel)
library(future)
library(clustree)
library(dittoSeq)
# install.packages("ggh4x")
library(ggh4x)
# BiocManager::install('EnhancedVolcano')
library(EnhancedVolcano)
library(clusterProfiler)
# BiocManager::install('org.Mm.eg.db')
library("org.Mm.eg.db")
library("org.Hs.eg.db")
# BiocManager::install('ReactomePA')
library(ReactomePA)
# BiocManager::install('msigdbr')
library(msigdbr)
# install.packages('qs')
library(qs)
# BiocManager::install('enrichR')
library(enrichR)
library(patchwork)
library(dplyr)
```

```{r global variables, include=FALSE}
set.seed(100)
DATADIR = '~/neuroblastoma/data/'
WORKDIR = '~/neuroblastoma/'
PREPRDATADIR = '~/neuroblastoma/preprocessing_data/'

my_colors <- c("#6495EDFF", "#FF69B4FF", "#BA55D3FF",  "#F08080FF", "#32CD32FF",  
               "#9ACD32FF", "#4682B4FF",  "#DDA0DDFF", "#FFA07AFF", "#8FBC8BFF",
               "#40E0D0FF",  "#F0E68CFF", "#5F9EA0FF", "#D2B48CFF",  
               "#FFDAB9FF",  "#87CEEBFF")
```

```{r}
seu <- qread(paste0(PREPRDATADIR, 'seu_mouse_neutrophils.qs'))
atlas <- qread(paste0(PREPRDATADIR, 'ATLAS_object.qs'))
```

```{r}
enableWGCNAThreads(nThreads = 8)
```

```{r}
DimPlot(seu, group.by='annotation', label=TRUE, cols = my_colors) +
   umap_theme() + ggtitle('Mouse annotation') + NoLegend()
```

# Setup object

v1 - Malignant_MOUSE

```{r}
seu <- SetupForWGCNA(
  seu,
  gene_select = "fraction", # the gene selection approach
  fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
  # group_by = 'annotation',
  wgcna_name = "v1" # the name of the hdWGCNA experiment
)
```

```{r}
# construct metacells  in each group
seu <- MetacellsByGroups(
  seurat_obj = seu,
  group.by = c("annotation", "age"), # specify the columns in seurat_obj@meta.data to group by
  reduction = 'harmony', # select the dimensionality reduction to perform KNN on
  k = 25, # nearest-neighbors parameter
  max_shared = 15, # maximum number of shared cells between two metacells
  ident.group = 'annotation' # set the Idents of the metacell seurat object
)

# normalize metacell expression matrix:
seu <- NormalizeMetacells(seu)
```

```{r}
seu <- SetDatExpr(
  seu,
  group_name = "Malignant_cells",
  group.by='annotation'
)
```

# Soft power

```{r}
seu <- TestSoftPowers(
  seu,
  networkType = 'signed' # you can also use "unsigned" or "signed hybrid"
)

# plot the results:
plot_list <- PlotSoftPowers(seu)

# assemble with patchwork
wrap_plots(plot_list, ncol=2)
```

# Construct network

```{r}
# construct co-expression network:
seu <- ConstructNetwork(
  seu,
  tom_name = 'Malignant_MOUSE', # name of the topoligical overlap matrix written to disk
  overwrite_tom = TRUE
)
```

```{r}
PlotDendrogram(seu, main='Mouse hdWGCNA Dendrogram')
```

```{r}
TOM <- GetTOM(seu)
```

# Modules

```{r}
# need to run ScaleData first or else harmony throws an error:
#seurat_obj <- ScaleData(seurat_obj, features=VariableFeatures(seurat_obj))

# compute all MEs in the full single-cell dataset
seu <- ModuleEigengenes(
 seu,
 group.by.vars="age"
)
```

```{r}
hMEs <- GetMEs(seu)
```

# Module connectivity

```{r}
# compute eigengene-based connectivity (kME):
seu <- ModuleConnectivity(
  seu,
  group.by = 'annotation', group_name = "Malignant_cells"
)
```

```{r fig.height=6, fig.width=12}
conflicted::conflict_prefer("select", "dplyr")
# plot genes ranked by kME for each module
p <- PlotKMEs(seu, ncol=6)
p
```

```{r fig.height=10, fig.width=10}
ModuleRadarPlot(
  seu,
  group.by = 'age',
  barcodes = seu@meta.data %>% subset(annotation == 'Malignant_cells') %>% rownames(),
  axis.label.size=4,
  grid.label.size=4
)
```

# DE

```{r}
group1 <- seu@meta.data %>% subset(annotation == 'Malignant_cells' & age == 'young') %>% rownames
group2 <- seu@meta.data %>% subset(annotation == 'Malignant_cells' & age == 'adult') %>% rownames

head(group1)
```

```{r}
DMEs <- FindDMEs(
  seu,
  barcodes1 = group1,
  barcodes2 = group2,
  test.use='wilcox',
  wgcna_name='v1'
)

head(DMEs)
```

```{r}
PlotDMEsLollipop(
  seu, 
  DMEs, 
  wgcna_name='v1', 
  pvalue = "p_val_adj"
)
```

# Signature score

```{r}
library(UCell)
seu <- ModuleExprScore(
  seu,
  n_genes = 50,
  method='UCell'
)
```

```{r fig.height=5, fig.width=10}
# make a featureplot of hMEs for each module
plot_list <- ModuleFeaturePlot(
  seu,
  features='hMEs', # plot the hMEs
  order=TRUE # order so the points with highest hMEs are on top
)

# stitch together with patchwork
wrap_plots(plot_list, ncol=6)
```

```{r fig.height=5, fig.width=10}
# make a featureplot of hub scores for each module
plot_list <- ModuleFeaturePlot(
  seu,
  features='scores', # plot the hub gene scores
  order='shuffle', # order so cells are shuffled
  ucell = TRUE # depending on Seurat vs UCell for gene scoring
)

# stitch together with patchwork
wrap_plots(plot_list, ncol=6)
```

# Modules analysis 

```{r}
# get the module assignment table:
modules <- GetModules(seu) %>% subset(module != 'grey')

modules %>% 
  dplyr::filter(module == 'purple') %>% 
  arrange(desc(kME_purple))
```

```{r fig.height=12, fig.width=4}
VlnPlot(subset(seu, annotation == 'Malignant_cells'), features = modules %>% 
          dplyr::filter(module == 'purple') %>% 
          arrange(desc(kME_purple)) %>% .$gene_name %>% .[1:20], group.by = 'age')
```


```{r}
# define the enrichr databases to test
dbs <- c('GO_Biological_Process_2023','GO_Cellular_Component_2023','GO_Molecular_Function_2023')

# perform enrichment tests
seu <- RunEnrichr(
  seu,
  dbs=dbs,
  max_genes = Inf # use max_genes = Inf to choose all genes
)

```

```{r}
# retrieve the output table
enrich_df <- GetEnrichrTable(seu)

enrich_df %>% 
  dplyr::filter(Adjusted.P.value < 0.05) %>% 
  dplyr::filter(module == 'turquoise')
  # dplyr::filter(module == 'black')
  # dplyr::filter(module == 'brown')
```

```{r eval=FALSE, include=FALSE}
# make GO term plots:
EnrichrBarPlot(
  seu,
  outdir = "enrichr_plots", # name of output directory
  n_terms = 10, # number of enriched terms to show (sometimes more are shown if there are ties)
  plot_size = c(5,7), # width, height of the output .pdfs
  logscale=TRUE # do you want to show the enrichment as a log scale?
)
```

Older mice’s tumors may rely more on glycolysis and hypoxia-driven pathways, which are associated with faster growth, metastasis, and therapy resistance.

```{r fig.height=20, fig.width=10}
# enrichr dotplot
EnrichrDotPlot(
  seu,
  mods = "all", # use all modules (default)
  database = "GO_Biological_Process_2023", # this must match one of the dbs used previously
  n_terms=5, # number of terms per module
  term_size=8, # font size for the terms
  p_adj = FALSE # show the p-val or adjusted p-val?
)  + scale_color_stepsn(colors=rev(viridis::magma(256)))
```

```{r eval=FALSE, include=FALSE}
qsave(seu, paste0(PREPRDATADIR, 'seu_WGCNA_malignant.qs'))
```

```{r}
seu <- qread(paste0(PREPRDATADIR, 'seu_WGCNA_malignant.qs'))
```

# Human

```{r}
library(biomaRt)

# Connect to Ensembl
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Get human-mouse orthologs
hg38_mm10_genes <- getBM(
  attributes = c("ensembl_gene_id", "external_gene_name", 
                 "mmusculus_homolog_ensembl_gene", "mmusculus_homolog_associated_gene_name"),
  mart = ensembl
)

# Rename columns
colnames(hg38_mm10_genes) <- c("hg38_id", "hg38_name", "mm10_id", "mm10_name")
hg38_mm10_genes <- dplyr::select(hg38_mm10_genes, c(hg38_name, mm10_name, hg38_id, mm10_id))

hg38_mm10_genes_unique <- hg38_mm10_genes[!duplicated(hg38_mm10_genes$hg38_name), ]

atlas_tumor <- ProjectModules(
  subset(atlas, Annotation == 'Neuroendocrine'),
  seurat_ref = seu,
  gene_mapping=as.data.frame(hg38_mm10_genes_unique),
  genome1_col="mm10_name", # genome of reference data
  genome2_col="hg38_name", # genome of query data
  wgcna_name_proj = "v1",
  modules = modules
)

# compute module hub scores for projected modules:
atlas_tumor <- ModuleExprScore(
  atlas_tumor,
  n_genes = 50,
  method='Seurat'
)
```

```{r eval=FALSE, include=FALSE}
qsave(atlas_tumor, paste0(PREPRDATADIR, 'atlas_tumor_WGCNA_mouse.qs'))
```

```{r}
atlas_tumor <- qread(paste0(PREPRDATADIR, 'atlas_tumor_WGCNA_mouse.qs'))
```

```{r}
sample_metadata <- read.csv(paste0(DATADIR, 'samples_metadata_v5.csv'))
sample_metadata[sample_metadata==""] <- NA

rownames(sample_metadata) <- sample_metadata$Sample_dataset



clean_sample_id <- function(id) {
  # First remove _rep1 and _rep2
  id <- gsub("_rep[12]$", "", id)
  
  # Handle the special bonine cases
  id <- gsub("_sn$", "", id)      # Remove _sn suffix
  id <- gsub("_[12]$", "", id)    # Remove _1 or _2 suffix
  
  return(id)
}

atlas_tumor$less18M <- sample_metadata[clean_sample_id(atlas_tumor$SampleID),]$less18M
```

## DE

```{r}
group1 <- atlas_tumor@meta.data %>% subset(Annotation == 'Neuroendocrine' & less18M == TRUE) %>% rownames
group2 <- atlas_tumor@meta.data %>% subset(Annotation == 'Neuroendocrine' & less18M == FALSE) %>% rownames
```

```{r}
DMEs_human <- FindDMEs(
  atlas_tumor,
  barcodes1 = group1,
  barcodes2 = group2,
  test.use='wilcox',
  wgcna_name='v1'
)

head(DMEs_human)
```

```{r}
PlotDMEsLollipop(
  atlas_tumor, 
  DMEs_human, 
  wgcna_name='v1', 
  pvalue = "p_val_adj"
)
```


# Networks

```{r}
ModuleNetworkPlot(
  seu,
  outdir = 'ModuleNetworks'
)
```



